name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: node:18-buster  # Utilisez une image de Docker Hub avec Node.js et installez pnpm dessus si nécessaire.

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: npx pnpm install

      - name: Build the project
        run: npx pnpm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
